backend:
  name: github
  repo: Carlos-Guo/lanse-stack
  branch: main
  base_url: https://www.lansetiankong.space
  auth_endpoint: /api/auth

site_url: https://www.lansetiankong.space
logo_url: /favicon.svg

media_folder: "static/uploads"
public_folder: "/uploads"

locale: "zh_Hans"

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "描述/摘要", name: "description", widget: "text", required: false }
      - { label: "分类", name: "categories", widget: "list", required: false }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "正文（Markdown）", name: "body", widget: "markdown" }
